name: tickle_game
description: A flutter game using flame engine

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flame: ^1.10.0
  vector_math: ^2.1.4
  lottie: ^2.7.0
  just_audio: ^0.9.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/bgm.mp3
    - assets/sounds/home-bgm.mp3  
    - assets/sounds/correct.mp3
    - assets/sounds/wrong.mp3
    - assets/sounds/combo.mp3
    - assets/sounds/start.mp3
    - assets/sounds/end.mp3
    - assets/sounds/click.mp3
    - assets/sounds/click.wav
